pipeline:
  build:
    image: docker
    commands:
      - docker build -t $DOCKER_IMAGE_NAME .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push $DOCKER_IMAGE_NAME
    environment:
      - DOCKER_IMAGE_NAME=azuracast/azuracast_web
      - DOCKER_USERNAME=$$DOCKER_USERNAME
      - DOCKER_PASSWORD=$$DOCKER_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock